### ISSUE TITLE
Default filename should be ~/friends.md instead of ./friends.md

### ISSUE THREAD

**Issue by meetmangukiya** [JacobEvelyn/friends#197]
Rather than having friends create a new friends.md file each time, the current directory doesn't have one; Why not just create and store data by default in some more permanent location, like `~/.friends.md` allowing users to use friends without caring about the current working directory?

**Comment by JacobEvelyn** [comment]
Hey @meetmangukiya! Thanks for the suggestion! Have you thought about using a shell alias like [this](https://github.com/JacobEvelyn/friends#syncing-across-multiple-machines) so that every time you call `friends` it uses the same file? (I'm not trying to dismiss your suggestion, just hoping to get more information about what solutions might achieve what you're looking for.)

**Comment by meetmangukiya** [comment]
@JacobEvelyn yes, this would work. But out of curiosity, do you think a user would want to have more than one friends.md file? Do you have any use case in mind? If not, I think friends should make only one file somewhere, and allow user to change that path, if he/she wants to.

**Comment by JacobEvelyn** [comment]
@meetmangukiya yeah I think that's reasonable. Would you be interested in making a PR for that change? (I'd be happy to provide guidance.)
