### ISSUE TITLE
Support Ruby 2.0?

### ISSUE THREAD

**Issue by balinthaller** [JacobEvelyn/friends#42]
Hey,

I'm not really familiar with the ruby ecosystem. I get the following error when trying to run any of the commands:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Library/Ruby/Gems/2.0.0/gems/friends-0.5/lib/friends/introvert.rb:55: syntax error, unexpected ')' (SyntaxError)
/Library/Ruby/Gems/2.0.0/gems/friends-0.5/lib/friends/introvert.rb:75: syntax error, unexpected ')'
/Library/Ruby/Gems/2.0.0/gems/friends-0.5/lib/friends/introvert.rb:103: syntax error, unexpected ')'
/Library/Ruby/Gems/2.0.0/gems/friends-0.5/lib/friends/introvert.rb:122: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/friends-0.5/bin/friends:12:in `<top (required)>'
	from /usr/local/bin/friends:23:in `load'
	from /usr/local/bin/friends:23:in `<main>'
```
I tried updating ruby using homebrew, but the error persists.

**Comment by JacobEvelyn** [comment]
Thanks for the bug report; I just noticed this myself. (It hadn't come up in development because Ruby versions 2.1+ don't produce this error, which is what I was using for development). I haven't gotten a chance to dig into the issue yet (it's likely very small) but in the meantime I've set a minimum Ruby version of 2.1 as a gem dependency in version 0.6.

If you have Ruby 2.1 you should be fine once you update the gem (`gem update friends`). If not, I'll add more to this thread once I know more about the issue but I expect to be able to get it working for Ruby 2.0 as well (which is what you're using, based on the error message).

**Comment by JacobEvelyn** [comment]
Ah, it looks like this is caused by the keyword method arguments I'm using, which I had thought were supported in Ruby 2.0 but the way I'm using them they're only in 2.1+. Would it be possible for you to update your Ruby version to 2.1 (or have multiple versions installed on your system)?

**Comment by balinthaller** [comment]
I installed rbenv, and 2.2.3, but it seems like the friends command is still trying to use 2.0. Trying to get around that now.

**Comment by JacobEvelyn** [comment]
You might have luck with `gem update friends`.

**Comment by balinthaller** [comment]
`gem update --system` solved the problem! (After updating to 2.2.3 using rbenv)

**Comment by JacobEvelyn** [comment]
Glad to hear it!

**Comment by balinthaller** [comment]
Thanks for the fast replies, hope this helps others with stock ruby.

**Comment by JacobEvelyn** [comment]
No problem!
